{
 "title": "Community.Extensions.Caching.AppMetrics",
 "tags": [ "influxdb" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "influxdb" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "SHOW TAG VALUES WITH KEY = \"env\""
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "SHOW TAG VALUES WITH KEY = \"inst\""
   },
   {
    "name": "application",
    "label": "Application",
    "query": "SHOW TAG VALUES WITH KEY = \"app\""
   },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES WITH KEY = \"server\""
   }
  ]
 },
 "panels": [
  {
   "title": "Total Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "memory 1 min rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cache.memory__t_count",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "inst", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "distributed 1 min rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cache.distributed__t_count",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "distributed read errors 1 min rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cache.distributed__e_count",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Distributed Cache Timings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "read time p99 milliseconds",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cache.distributed__r_time",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "inst", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "miss time p99 ms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cache.distributed__f_time",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "write time p99 ms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cache.distributed__w_time",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hit and Error Ratio",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "memory hit ratio minute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cache.memory__h_ratio_minute",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "inst", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "distributed hit ratio minute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cache.distributed__h_ratio_minute",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "distributed error ratio minute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cache.distributed__e_ratio_minute",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}